sonar.projectKey=Nachobt98_component-library
sonar.organization=nachobt98

sonar.projectName=component-library
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js
sonar.exclusions=dist/**,coverage/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
